# データとモデルの保存場所
data_dir: '/aichallenge/record/preprocessed/at/'
save_dir: './ckpts'

# 学習ハイパーパラメータ
training:
  epochs: 20
  batch_size: 32
  learning_rate: 0.0001

# データローダ設定
dataloader:
  num_workers: 16

# モデル設定
model:
  name: 'resnet18'
  ema_decay: 0.999