# (任意) 使用するCPUコア数。
num_workers: 8

# データキー設定
data_keys:
  scan_dataset: 'scan'
  control_dataset: 'control_cmd'
  time_columns:
    sec: 'sec'
    nanosec: 'nanosec'
    timestamp: 'timestamp'
  scan_columns:
    ranges: 'ranges'
    intensities: 'intensities'

# 前処理パラメータ
preprocessing:
  sync:
    tolerance_seconds: 0.02
    merge_suffix: '_control'
  cleaning:
    default_range_max: 30.0
    replace_nan_with: 0.0
    replace_posinf_with: 0.0
    replace_neginf_with: 0.0

# 出力設定
output:
  control_columns_to_write:
    - 'speed'
    - 'acceleration'
    - 'steering_tire_angle'
    - 'steering_tire_rotation_rate'