# データセットに関する設定
data:
  train_dir: "/aichallenge/dataset/train"
  val_dir: "/aichallenge/dataset/val"
  sequence_length: 1                   
  slide_step: 1
  load_into_memory: False
  scan_num_points: 1080

# モデルに関する設定
model:
  name: "TinyLidarNet"
  input_dim: 1080
  output_dim: 2

# 学習に関する設定
train:
  batch_size: 32
  epochs: 100
  lr: 0.0001                                         
  num_workers: 16
  save_dir: "ckpts/train/${now:%Y-%m-%d}/${now:%H-%M-%S}/"
  log_dir: "logs/train/${now:%Y-%m-%d}/${now:%H-%M-%S}/"

  # 損失関数の重み
  loss:
    accel_weight: 0.0
    steer_weight: 1.0

  # 指定したら再学習を行う
  pretrained_path: null


# Hydraの実行ディレクトリ設定
hydra:
  run:
    dir: ./outputs/train/${now:%Y-%m-%d}/${now:%H-%M-%S}